
name: CMake CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    name: Ubuntu 20.04 Build and Test
    steps:
      - uses: actions/checkout@v2

      - name: Resolve dependencies
        run: sudo apt-get install libarmadillo-dev cmake gfortran libgsl-dev libxc-dev libxc5 libint1 libint-dev

      - name: Compile
        run: mkdir build && cd build && cmake -E env CXXFLAGS="-DARMA_DONT_USE_WRAPPER" cmake .. && make

      - name: Test
        run: cd ./build/tests && make test
